global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: auth-service
    metrics_path: /metrics
    static_configs:
      - targets: ['auth-service:4000']

  - job_name: user-service
    metrics_path: /metrics
    static_configs:
      - targets: ['user-service:4001']

  - job_name: catalog-service
    metrics_path: /metrics
    static_configs:
      - targets: ['catalog-service:4002']

  - job_name: media-service
    metrics_path: /metrics
    static_configs:
      - targets: ['media-service:4003']

  - job_name: library-service
    metrics_path: /metrics
    static_configs:
      - targets: ['library-service:4004']

  - job_name: playback-service
    metrics_path: /metrics
    static_configs:
      - targets: ['playback-service:4005']
